e1: 
	g++ -fopenmp Exercise_1/openmp_sieve.cpp -o a.out

e1_orig:
	g++ Exercise_1/sieve.cpp -o a.out

e2:
	g++ -fopenmp Exercise_2/Game_Of_Life_OpenMP.c -o a.out

e3_outer: 
	g++ -fopenmp Exercise_3/matrix_outer_loop.cpp -o a.out

e3_two_outer: 
	g++ -fopenmp Exercise_3/matrix_two_outer_loop.cpp -o a.out